spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop #create/create-drop/update
    show-sql: true
    open-in-view: false #fixed
    properties:
      hibernate:
        format_sql: true    #dev
        highlight_sql: true   #dev
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true
